apiVersion: v2
name: odh
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "odh"
    version: "0.6.0"
    repository: "https://rh-intelligent-application-practice.github.io/helm-charts/"
