apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-demo-kafka
spec:
  destination:
    namespace: mlops-demo-dev
    server: https://kubernetes.default.svc
  project: mlops-demo-dev
  source:
    path: components/charts/kafka/
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
