apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-tag
  annotations:
    description: |
      Generate a new unique image tag based on format YYYY-MM-YY-HH-MM-SS.
spec:
  results:
    - name: image-tag
      description: The current date in human readable format
  steps:
    - name: generate-image-tag
      image: docker.io/alpine/git:v2.26.2
      script: |
        #!/usr/bin/env bash
        set -e
        
        # get the git sha
        sha=$(git rev-parse --short HEAD)

        # get the ml-model version
        model_version="1"

        # generate the current date/time
        date=$(date +"%Y%m%d-%H%M%S")

        tag=$(${sha}-${model_version}-${date})

        echo ${tag} | tee $(results.image-tag.path)
