apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: iris-inference-service-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-iris-inference-service
