name: Manifests Validation
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  kustomize-lint:
    runs-on: ubuntu-latest
    env:
      KUSTOMIZE_VERSION: 3.9.4
    steps:
      - name: Install Kustomize
        run: |
          sudo curl -L -o /usr/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64
          sudo chmod +x /usr/bin/kustomize
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Validate Manifests
        run: ./validate_manifests.sh
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Validate Manifests
        run: yamllint . -f github
  helm-lint:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: 3.9.4
    steps:
      - name: Install Helm
        run: |
          sudo curl -L -o /usr/bin/helm https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
          sudo chmod +x /usr/bin/helm
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Validate Manifests
        run: helm lint components/charts/odh/
